sudo: required
dist: trusty

services:
  - docker

install:
  # Install docker engine from Docker's Ubuntu repo
  - curl -sSL https://get.docker.com/gpg | sudo -E apt-key add -
  - echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --assume-yes install docker-engine
  - docker version

  # Update docker-compose via pip
  - sudo pip install docker-compose
  - docker-compose version

before_script:
  - docker-compose up --build -d

script:
  - ./test.sh

after_script:
  - docker-compose down

after_failure:
  - docker logs sabnzbd

after_success:
  - docker history dockersabnzbd_sabnzbd
